In [49]:
import pandas as pd
import numpy as np
import random as rd
import math

In [50]:
df = pd.read_excel('Data_Tugas_Akhir.xlsx', sheetname='Data_latih')
target = pd.read_excel('Data_Tugas_Akhir.xlsx', sheetname='Target')

In [51]:
dfNormalisasi = (df - df.mean())/(df.max() - df.min())
ValueTarget = np.array(target['target'])

In [80]:
alfa = 0.1
input_unit = 6
output_unit = 3
hidden_layer = 2

In [81]:
target_data_latih = [
    [1, 0, 0], #Kelas1
    [0, 1, 0], #Kelas2
    [0, 0, 1]  #Kelas3
]

In [82]:
#InputanAwalBebasUntukProsesNguyen
VijLama = np.random.uniform(-0.5, 0.5, (hidden_layer, input_unit))
VijLama

array([[-0.35102179,  0.36296342, -0.46472295,  0.17309224,  0.45489152,
        -0.4867072 ],
       [ 0.17433989,  0.40309064,  0.48231603, -0.27012614,  0.39763465,
         0.10746092]])

In [83]:
#SetNilaiBeta
valueB = 0.7*((hidden_layer)**1/input_unit)
valueB

0.2333333333333333

In [84]:
def valueMutlak(hidden_layer, dataInput):
    MatriksKosong = []
    for col in range (0, hidden_layer):
        for value in dataInput:
            valueV = math.sqrt(value[col]**2)
        MatriksKosong.append(valueV)
    return MatriksKosong

In [85]:
MutlakV = valueMutlak(hidden_layer, VijLama)
MutlakV

[0.17433988549678237, 0.4030906375606462]

In [90]:
#Method Untuk Mendapatkan Weigth Berdasarkan Nguyen
def NguyenWidrow(mutlak, valueB, dataInput):
    bantu = []
    ValueNewV = []
    for baris in range(0, hidden_layer):
        for kolom in range(0, input_unit):
            valueV = valueB * dataInput[baris][kolom] / MutlakV[baris]
            bantu.append(valueV)
    ValueNewV.append(bantu)
    ValueBaru = np.reshape(ValueNewV, (2,6))
    return ValueBaru

In [91]:
#Methode untuk mendapatkan Bias Hidden Layer
def getValueBiasNew(valueB):
    BiasBaru = np.random.uniform(-valueB, valueB, (2))
    return BiasBaru

FUNGSI AKTIVASI

In [92]:
def arctangenFunction(x):
    phi = 3.14159265358979323846
    ValueTan = math.atan(x)
    return (2 /phi) * ValueTan
    

In [93]:
def arctangenFunctionDerivative(x):
    phi = 3.14159265358979323846
    Value = 1 / 1 + math.pow(x, 2)
    return (2 /phi) * Value

In [94]:
def fungsi_aktivasi(x):
#     nilai = x
    Value = 1+ np.exp(-x)
    return 1/Value

In [95]:
def fungsi_aktivasi_turunan(x) :
    pengkali = 1 - fungsi_aktivasi(x)
    return fungsi_aktivasi(x)*pengkali

INISIALISASI BOBOT

In [96]:
#Bias Hidden Layer
ValueV0jHidden = getValueBiasNew(valueB)

In [97]:
ValueV0jHidden

array([-0.15832063,  0.1423964 ])

In [98]:
#Bobot Hidden Layer
ValueVijHidden = NguyenWidrow(MutlakV, valueB, VijLama) 
ValueVijHidden

array([[-0.46980118,  0.48578365, -0.62197675,  0.23166351,  0.60881855,
        -0.65140006],
       [ 0.10091851,  0.23333333,  0.2791938 , -0.15636541,  0.23017508,
         0.06220491]])

In [99]:
#BobotOutputLayer
ValueWjkOutput = np.random.uniform(-0.5, 0.5, (output_unit, hidden_layer))
ValueWjkOutput

array([[ 0.28231144,  0.14885628],
       [ 0.42347058, -0.20889018],
       [ 0.33592296,  0.32002966]])

In [100]:
#Bias Output Layer
ValueW0kOutput = np.random.uniform(-0.5, 0.5, (3))
ValueW0kOutput

array([-0.03702895, -0.3737435 ,  0.26536223])

PROSES

In [78]:
def getFeedForward(dataLatih, Bobot_Hidden, Bias_Hidden, Bias_Output, Bobot_Output):
    ValueZ = []
    ValueY = []
    ValueZin = []
    ValueYin = []
    Bantu = []
    #Mencari Nilai Zin = Vij * x + V0j
    #Sekaligus Mendapatkan Nilai Z yang telah dilakukan Aktivasi
    for key, value in dataLatih.iterrows():
        for baris in range(0, hidden_layer):
            for kolom in range(0, input_unit):
                NilaiZin = sum(Bobot_Hidden[baris][kolom] * value)
            bantu = NilaiZin + Bias_Hidden[baris]
            Bantu.append(bantu)
            z = [fungsi_aktivasi(i) for i in Bantu]
        ValueZin.append(Bantu)
        Bantu = []
        ValueZ.append(z)

    #Mencari nilai Yin = Wjk * z + W0k
    #Sekaligus Mendapatkan Nilai Y yang telah dilakukan Aktivasi
    NilaiBantu = 0
    for key, value in dataLatih.iterrows():
        for baris in range (len(Bobot_Output)):
            for kolom in range (len(Bobot_Output[0])):
                NilaiYin = ValueZ[baris][kolom] * Bobot_Output[baris][kolom]
                NilaiBantu += NilaiYin
            NilaiYin = NilaiBantu + Bias_Output[baris]
            Bantu.append(NilaiYin)
            y = [fungsi_aktivasi(i) for i in Bantu]
        ValueYin.append(Bantu)
        Bantu = []
        ValueY.append(y)
        
#     print(Val)
#     print(ValueY)
    return ValueZ, ValueY, ValueZin, ValueYin

In [79]:
ValueZ, ValueY, ValueZin, ValueYin = getFeedForward(dfNormalisasi, ValueVijHidden, ValueV0jHidden, ValueW0kOutput, ValueWjkOutput)

IndexError: index 2 is out of bounds for axis 0 with size 2

In [26]:
ValueYin

[[0.21445739387360702, 0.5130614874353165, -0.0359744452113121],
 [0.5364100107817753, 0.8350141043434848, 0.28597817169685613],
 [0.8583626276899436, 1.1569667212516532, 0.6079307886050245],
 [1.180315244598112, 1.4789193381598214, 0.9298834055131929],
 [1.5022678615062803, 1.80087195506799, 1.2518360224213612],
 [1.8242204784144487, 2.122824571976158, 1.5737886393295297],
 [2.1461730953226175, 2.4447771888843266, 1.8957412562376978],
 [2.468125712230785, 2.7667298057924947, 2.217693873145866],
 [2.7900783291389537, 3.088682422700663, 2.539646490054034],
 [3.1120309460471214, 3.410635039608831, 2.861599106962202],
 [3.43398356295529, 3.732587656516999, 3.1835517238703703],
 [3.7559361798634576, 4.054540273425167, 3.5055043407785385],
 [4.077888796771626, 4.376492890333335, 3.8274569576867066],
 [4.399841413679794, 4.698445507241503, 4.149409574594874],
 [4.7217940305879615, 5.02039812414967, 4.471362191503042],
 [5.043746647496129, 5.342350741057838, 4.79331480841121],
 [5.36569926440

In [27]:
def BackPreprogration(dfNormalisasi,Yin, ValueY, target, alfa, ValueZ, ValueWjk, Zin):
    ValueDk = []
    ValueDw = []
    ValueDw0 = []
    ValueDin = []
    ValueDz = []
    ValueDv = []
    ValueDv0 = []
    ValueYinAkitvasiTurunan = []
    ValueZinAkitvasiTurunan = []
    Bantu = []
    Bantu2 = []
    
    TargetComvert = [
    [1, 0, 0], #Kelas1
    [0, 1, 0], #Kelas2
    [0, 0, 1]  #Kelas3
]
    for baris in range (len(Yin)):
        YinNew = [fungsi_aktivasi_turunan(i) for i in Yin[baris]]
        ValueYinAkitvasiTurunan.append(YinNew)
        
#     Hitung  δk
    for baris in range (len(ValueY)):
        for kolom in range(len(ValueY[0])):
            if(target[baris] == 1):
                NilaiDk = (TargetComvert[0][kolom] - ValueY[baris][kolom]) * ValueYinAkitvasiTurunan[baris][kolom]
            elif(target[baris] == 2):
                NilaiDk = (TargetComvert[1][kolom] - ValueY[baris][kolom]) * ValueYinAkitvasiTurunan[baris][kolom]
            elif(target[baris] == 3):
                NilaiDk = (TargetComvert[2][kolom] - ValueY[baris][kolom]) * ValueYinAkitvasiTurunan[baris][kolom]
            Bantu.append(NilaiDk)
        ValueDk.append(Bantu)
        Bantu = []
        
    #Hitung ΔWjk
    for baris in range (len(ValueDk)):
        for kolom in range (len(ValueDk[0])):
            for kolom1 in range(len(ValueZ[0])):
                NilaiDw = ValueDk[baris][kolom] * ValueZ[baris][kolom1] * alfa
                Bantu.append(NilaiDw)
            Bantu2.append(Bantu)
            Bantu = []
        ValueDw.append(Bantu2)
        Bantu2 = []
    
    #Hitung ΔW0k alfa * Dk
    for baris in range(len(ValueDk)):
        NilaiDw0 = [i * alfa for i in ValueDk[baris]]
        ValueDw0.append(NilaiDw0)
#     print(ValueDw0)
    
    transpose_wjk = np.transpose(ValueWjk)
    
#     Hitung δin = δk * Wjk
    for i in range (len(dfNormalisasi)):
        NilaiBantu = 0
        for baris in range (len(transpose_wjk)):
            for kolom in range (len(transpose_wjk[0])):
                NilaiDin = ValueDk[i][kolom] * transpose_wjk[baris][kolom]
                NilaiBantu += NilaiDin
            Bantu.append(NilaiBantu)
        ValueDin.append(Bantu)
        Bantu = []
        NilaiBantu = 0
#     print(ValueDin)
    #Hitung Dz
    for baris in range(len(Zin)):
        for kolom in range (len(Zin[0])):
            ZinAktivasiTurunan = fungsi_aktivasi_turunan(Zin[baris][kolom])
            Bantu.append(ZinAktivasiTurunan)
        ValueZinAkitvasiTurunan.append(Bantu)
        Bantu = []
#     print(ValueZinAkitvasiTurunan)
    for baris in range(len(ValueDin)):
        for kolom in range(len(ValueDin[0])):
            NilaiDz = ValueDin[baris][kolom] * ValueZinAkitvasiTurunan[baris][kolom]
            Bantu.append(NilaiDz)
        ValueDz.append(Bantu)
        Bantu = []
        
    #Hitung ΔVij
    Data = np.array(dfNormalisasi)
    for baris in range (len(Data)):
        for kolom in range(len(ValueDz[0])):
            for kolom1 in range(0, input_unit):
                NilaiVij = alfa * Data[baris][kolom1] * ValueDz[baris][kolom]
                Bantu.append(NilaiVij)
            Bantu2.append(Bantu)
            Bantu = []
        ValueDv.append(Bantu2)
        Bantu2 = []
        
    #Hitung ΔV0j
    for baris in range (len(ValueDz)):
        for kolom in range(len(ValueDz[0])):
            NilaiV0j = alfa * ValueDz[baris][kolom]
            Bantu.append(NilaiV0j)
        ValueDv0.append(Bantu)
        Bantu = []
        
    return ValueDw, ValueDw0, ValueDv, ValueDv0

In [28]:
ValueDw, ValueDw0, ValueDv, ValueDv0 = BackPreprogration(dfNormalisasi,ValueYin, ValueY, ValueTarget, alfa, ValueZ, ValueWjkOutput, ValueZin)

In [29]:
ValueDv

[[[0.00010538919005369234,
   -8.552855070107468e-05,
   -0.0001019260815196272,
   -6.638940868115233e-05,
   9.478623018785533e-05,
   -8.369877894893789e-05],
  [0.0002177993751674183,
   -0.0001767549868461702,
   -0.0002106424468859497,
   -0.0001372016591181949,
   0.00019588708954753652,
   -0.00017297354451692042]],
 [[9.17453462470978e-06,
   5.798566279575452e-05,
   -1.239500861892388e-05,
   -9.854048507342852e-05,
   3.112547740198988e-05,
   5.6000586271827064e-05],
  [2.1989867044199508e-05,
   0.0001389822010060552,
   -2.970881932340685e-05,
   -0.0002361855128214926,
   7.46027060504603e-05,
   0.00013422429549702155]],
 [[-3.9023351215513555e-06,
   9.50658126205433e-06,
   3.309818844041433e-06,
   -6.03985047194845e-06,
   2.369040909582883e-06,
   9.285929381693147e-06],
  [-2.3585760486824164e-05,
   5.745789167543519e-05,
   2.000458496739876e-05,
   -3.6504929015675086e-05,
   1.4318511797801936e-05,
   5.612426905229735e-05]],
 [[-2.2006672435484135e-05,
   2.

In [30]:
ValueWjkOutput

array([[ 0.24269534,  0.269996  ],
       [-0.07274239,  0.07108115],
       [ 0.16123288,  0.0049014 ]])

In [31]:
def UpdateBobot(ValueWjk, ValueDw, ValueDw0, ValueW0, ValueDv0, ValueV0, ValueVij, ValueDv):
    Miu = 0.175
    
    #UpdateBobotVij
    for baris in range (len(ValueDv)):
        for kolom1 in range (len(ValueDv[0])):
            for kolom in range(len(ValueVij[0])):
                NilaiVbaru = ValueDv[baris][kolom1][kolom] + (Miu * ValueVij[kolom1][kolom])
                ValueVij[kolom1][kolom] = NilaiVbaru
#     print(ValueVij)
    #UpdateBobotW0j
    for baris in range(len(ValueDv0)):
        for kolom in range(len(ValueDv0[0])):    
            NilaiW0Baru = (ValueDv0[baris][kolom] + ValueV0[kolom])
            ValueV0[kolom] = NilaiW0Baru
            
    #UpdateBiasNewW0
    for baris in range(len(ValueDw0)):
        for kolom in range(len(ValueDw0[0])):
            NilaiBiasHiddenBaru = ValueDw0[baris][kolom] + ValueW0[kolom]
            ValueW0[kolom] = NilaiBiasHiddenBaru
#     print(ValueW0)

    #UpdateBiasNewWjk
    for baris in range(len(ValueDw)):
        for indeks2d in range(len(ValueDw[0])):
            for kolom in range(len(ValueWjk[0])):
                NilaiWBaru = ValueDw[baris][indeks2d][kolom] + (Miu*ValueWjk[indeks2d][kolom])
                ValueWjk[indeks2d][kolom] = NilaiWBaru
#     print(ValueWjk)
    return ValueVij,ValueV0, ValueW0, ValueWjk

In [32]:
def CheckError(ValueY, target):
    TargetComvert = [
        [1, 0, 0], #Kelas1
        [0, 1, 0], #Kelas2
        [0, 0, 1]  #Kelas3
    ]
    Error = []
    Bantu = []
    for baris in range (len(ValueY)):
        for kolom in range(len(ValueY[0])):
            if(target[baris] == 1):
                NilaiError = math.pow((ValueY[baris][kolom] - TargetComvert[0][kolom]),2)
            elif(target[baris] == 2):
                NilaiError = math.pow((ValueY[baris][kolom] - TargetComvert[1][kolom]),2)
            elif(target[baris] == 3):
                NilaiError = math.pow((ValueY[baris][kolom] - TargetComvert[2][kolom]),2)
            Bantu.append(NilaiError)
        Error.append(Bantu)
        Bantu = []
    Jumlah_ErrorPerBaris = 0
    JumlahKeseluruhan = []
    for baris in range(len(Error)):
        for kolom in range(len(Error[0])):
            Jumlah_ErrorPerBaris += Error[baris][kolom]
        JumlahKeseluruhan.append(Jumlah_ErrorPerBaris)
    TotalError1Epoch = 0
    for baris in range(len(JumlahKeseluruhan)):
        TotalError1Epoch += JumlahKeseluruhan[baris]
    NilaiRMSE = math.sqrt(TotalError1Epoch / len(JumlahKeseluruhan))
    return NilaiRMSE
#     print(NilaiRMSE)
        

In [33]:
def MencariBobotOptimal(dfNormalisasi, ValueVijHidden, ValueV0jHidden, ValueW0kOutput, ValueWjkOutput):
    Epoch = 0
    MaxEpoch = 1000
    updateError = 0
    NilaiRMSE = 0
    while(Epoch < MaxEpoch or updateError < NilaiRMSE):
        ValueZ, ValueY, ValueZin, ValueYin = getFeedForward(dfNormalisasi, ValueVijHidden, ValueV0jHidden, ValueW0kOutput, ValueWjkOutput)
        ValueDw, ValueDw0, ValueDv, ValueDv0 = BackPreprogration(dfNormalisasi,ValueYin, ValueY, ValueTarget, alfa, ValueZ, ValueWjkOutput, ValueZin)
        ValueVijHidden, ValueV0jHidden, ValueW0kOutput, ValueWjkOutput = UpdateBobot(ValueWjkOutput, ValueDw, ValueDw0, ValueW0kOutput, ValueDv0, ValueV0jHidden, ValueVijHidden, ValueDv)
        NilaiRMSE = CheckError(ValueY, ValueTarget)
        updateError = NilaiRMSE
        Epoch += 1
    print(Epoch)
    
    return ValueVijHidden, ValueV0jHidden, ValueW0kOutput, ValueWjkOutput

In [34]:
NilaiVij, NilaiV0, NilaiW0, NilaiWjk = MencariBobotOptimal(dfNormalisasi, ValueVijHidden, ValueV0jHidden, ValueW0kOutput, ValueWjkOutput)

1000


In [35]:
NilaiVij

array([[-1.40488255e-05,  1.17704147e-05,  1.30529565e-05,
         9.55965409e-06,  5.89357766e-07,  1.15316615e-05],
       [-2.88410164e-05,  2.41636372e-05,  2.67965835e-05,
         1.96251373e-05,  1.20989936e-06,  2.36734977e-05]])

In [36]:
NilaiV0

array([-0.18481678, -0.1089955 ])

In [37]:
NilaiW0

array([-0.60734144, -0.60516763, -0.84337272])

In [38]:
NilaiWjk

array([[-0.00436519, -0.00454648],
       [-0.00435672, -0.00453767],
       [ 0.00808116,  0.00841679]])

In [39]:
DataUji = pd.read_excel('Data_Tugas_Akhir.xlsx', sheetname='Data_Uji')
DataUjiNormalisasi = (DataUji - DataUji.mean())/(DataUji.max() - DataUji.min())

In [40]:
ValueZDataUji, ValueYUji, ValueZinUji, ValueYinDataUji = getFeedForward(DataUjiNormalisasi, NilaiVij, NilaiV0, NilaiW0, NilaiWjk)

In [41]:
ValueYUji

[[0.3517234029936548, 0.35127911270277845, 0.3006974140186109],
 [0.3515851646437275, 0.3511409543894278, 0.3005699321784855],
 [0.35144695117107183, 0.3510028210133539, 0.30044248116473243],
 [0.35130876259437177, 0.35086471259318996, 0.30031506098959077],
 [0.35117059893229574, 0.35072662914755315, 0.3001876716652823],
 [0.3510324602034961, 0.35058857069504473, 0.3000603132040119],
 [0.35089434642660927, 0.35045053725424996, 0.2999329856179666],
 [0.350756257620256, 0.3503125288437384, 0.29980568891931675],
 [0.3506181938030408, 0.3501745454820635, 0.29967842312021514]]

In [43]:
def Pengujian(dataLatih,ValueVij, ValueV0, ValueW0, ValueWjk, ValueZin, ValueZ):
    Bantu = []
    ValueZin = []
    ValueYin = []
    ValueZ = []
    ValueY = []
    
    #Perhitungan Input Pada Hidden Neuron
    #Zin = Vij * x + V0j
    for key, value in dataLatih.iterrows():
        for baris in range(0, hidden_layer):
            for kolom in range(0, input_unit):
                NilaiZin = sum(ValueVij[baris][kolom] * value)
            bantu = NilaiZin + ValueV0[baris]
            Bantu.append(bantu)
            z = [fungsi_aktivasi(i) for i in Bantu]
        ValueZin.append(Bantu)
        Bantu = []
        ValueZ.append(z)
    
    NilaiBantu = 0
    for key, value in dataLatih.iterrows():
        for baris in range (len(ValueWjk)):
            for kolom in range (len(ValueWjk[0])):
                NilaiYin = ValueZ[baris][kolom] * ValueWjk[baris][kolom]
                NilaiBantu += NilaiYin
            NilaiYin = NilaiBantu + ValueW0[baris]
            Bantu.append(NilaiYin)
            y = [fungsi_aktivasi(i) for i in Bantu]
        ValueYin.append(Bantu)
        Bantu = []
        ValueY.append(y)
    print(ValueY)
    
    

In [44]:
y = Pengujian(dfNormalisasi, NilaiVij, NilaiV0, NilaiW0, NilaiWjk, ValueZin, ValueZ)

[[0.35172340182242745, 0.3512790978892014, 0.3006974127796457], [0.35158516212948904, 0.35114093823607956, 0.30056992970115415], [0.3514469473143059, 0.3510028035207213, 0.30044247744963426], [0.351308757395563, 0.3508646937617604, 0.3003150560373255], [0.3511705923919289, 0.3507266089778145, 0.3001876654764501], [0.35103245232205665, 0.35058854918748544, 0.30006030577921305], [0.35089433720458324, 0.35045051440935915, 0.29993297695780197], [0.35075624705812997, 0.3503125046620056, 0.29980567902438743], [0.35061818190130195, 0.3501745199639787, 0.29967841199112266], [0.3504801417526885, 0.35003656033381664, 0.29955117587014346], [0.35034212663086295, 0.34989862579004155, 0.29942397067356863], [0.3502041365543828, 0.34976071635115963, 0.29929679641349954], [0.35006617154178976, 0.34962283203566114, 0.2991696531020204], [0.3499282316116091, 0.3494849728620202, 0.29904254075119824], [0.3497903167823505, 0.3493471388486951, 0.29891545937308256], [0.34965242707250765, 0.3492093300141283, 0.

In [45]:
def one_hot_encoding(y):
    if(y.index(max(y)) == 0):
        target = 1
    elif(y.index(max(y)) == 1):
        target = 2
    elif(y.index(max(y)) == 2):
        target = 3

    return target

In [47]:
y_class = []
for x in ValueY:
    y = one_hot_encoding(x)
    y_class.append(y)
    
y_class

[2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2]

In [48]:
accu = 0
for i in range(0, len(y_class)):
    if(y_class[i] == ValueTarget[i]):
        accu += 1

acc = accu/len(y_class) * 100

acc

35.0